const { chromium }=require('@playwright/test');
const assert=require('node:assert/strict');
const {pathToFileURL}=require('node:url');
(async()=>{
 const browser=await chromium.launch({headless:true});
 try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(pathToFileURL(process.cwd()+'/index.html').href);await page.waitForFunction(()=>typeof deck!=='undefined'&&deck.isReady());await page.evaluate(()=>document.fonts.ready);
 const ids=['home','overview','flow','verification','eligibility','developers','economics','calculator-slide','competition','funding-sources','banks','nbfcs','embedded-finance','licensing','licensing-requirements','developer-finance','sources'];
 for(let i=0;i<ids.length;i++){await page.evaluate(i=>deck.slide(i),i);await page.waitForTimeout(300);await page.screenshot({path:'.build/'+ids[i]+'.png'});const overflow=await page.locator('#'+ids[i]).evaluate(el=>{const r=el.getBoundingClientRect();return [...el.querySelectorAll('*')].filter(x=>x.getClientRects().length&&getComputedStyle(x).position!=='absolute').filter(x=>{const b=x.getBoundingClientRect();return b.bottom>r.bottom+2||b.right>r.right+2}).map(x=>x.id||x.className||x.tagName)});assert.deepEqual(overflow,[],ids[i]+' overflow: '+overflow);}
 for(const target of ['banks','nbfcs','embedded-finance']){await page.evaluate(()=>deck.slide([...document.querySelectorAll('.slides>section')].findIndex(s=>s.id==='funding-sources')));await page.locator('#funding-sources a[href="#/'+target+'"]').click();await page.waitForFunction(id=>deck.getCurrentSlide().id===id,target);await page.locator('#'+target+' .funding-back').click();await page.waitForFunction(()=>deck.getCurrentSlide().id==='funding-sources');}
 await page.evaluate(()=>deck.slide(7));await page.waitForTimeout(300);assert.equal(await page.locator('#retained').textContent(),'2.33M');
 await page.locator('#marketMode').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#processedMode').getAttribute('aria-selected'),'true');assert.equal(await page.locator('#volume').textContent(),'AED 90M');await page.keyboard.press('Home');assert.equal(await page.locator('#marketMode').getAttribute('aria-selected'),'true');assert.equal(await page.evaluate(()=>deck.getIndices().h),7);await page.locator('#marketUnitTrigger').click();assert(await page.locator('#marketUnitMenu').isVisible());await page.screenshot({path:'.build/unit-menu.png'});await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');assert.equal(await page.locator('#marketUnit').inputValue(),'1000000');assert.equal(await page.locator('#retained').textContent(),'2.33K');await page.locator('#marketUnitTrigger').click();await page.keyboard.press('Escape');assert.equal(await page.locator('#marketUnitMenu').isVisible(),false);assert.equal(await page.evaluate(()=>deck.getIndices().h),7);await page.locator('#reset').click();assert.equal(await page.locator('#marketUnitTrigger span').textContent(),'B');
 await page.locator('#processedMode').click();assert.equal(await page.locator('#volume').textContent(),'AED 90M');assert.equal(await page.locator('#retained').textContent(),'1.71M');
 await page.locator('#advance').fill('100');assert.equal(await page.locator('#volume').textContent(),'AED 100M');
 await page.locator('#rate').fill('10');await page.locator('#days').fill('120');assert.equal(await page.locator('#retained').textContent(),'-333.33K');
 await page.locator('#days').press('ArrowUp');assert.equal(await page.evaluate(()=>deck.getIndices().h),7);
 await page.locator('#processed').fill('');assert.equal(await page.locator('#results').isVisible(),true);assert.equal(await page.locator('#retained').textContent(),'0');assert.equal(await page.locator('#error').textContent(),'');assert(await page.locator('#results').evaluate(el=>el.classList.contains('is-pending')));await page.locator('#processed').fill('100');assert.equal(await page.locator('#results').evaluate(el=>el.classList.contains('is-pending')),false);
 await page.locator('#reset').click();assert.equal(await page.locator('#retained').textContent(),'2.33M');
 await page.locator('#share').fill('');assert.equal(await page.locator('#retained').textContent(),'0');assert.equal(await page.locator('#share').getAttribute('placeholder'),'0');await page.screenshot({path:'.build/calculator-empty.png'});await page.locator('#share').fill('101');assert.equal(await page.locator('#share').getAttribute('aria-invalid'),'true');assert(await page.locator('#shareFeedback').isVisible());await page.locator('#share').fill('1');assert.equal(await page.locator('#retained').textContent(),'2.33M');await page.locator('summary').click();await page.locator('#basisTrigger').click();await page.screenshot({path:'.build/basis-menu.png'});await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');assert.equal(await page.locator('#basis').inputValue(),'365');assert.equal(await page.locator('#retained').textContent(),'2.34M');await page.locator('#basisTrigger').click();await page.keyboard.press('Home');await page.keyboard.press('Enter');assert.equal(await page.locator('#basis').inputValue(),'360');await page.screenshot({path:'.build/calculator-expanded.png'});
 const expanded=await page.locator('#calculator-slide').evaluate(e=>e.scrollHeight<=e.clientHeight);assert(expanded,'Expanded calculator overflows');
 await page.locator('#viewToggle').click();assert(await page.locator('body').evaluate(e=>e.classList.contains('reader')));await page.locator('.site-nav a[href="#/flow"]').click();await page.waitForTimeout(600);assert(await page.locator('#flow').isVisible());
 await page.locator('#viewToggle').click();assert.equal(await page.evaluate(()=>deck.getIndices().h),2);
 const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});mobile.on('pageerror',e=>errors.push(e.message));await mobile.goto(pathToFileURL(process.cwd()+'/index.html').href);await mobile.waitForFunction(()=>document.body.classList.contains('reader'));await mobile.waitForTimeout(500);assert.equal(await mobile.locator('.slides>section[inert]').count(),0);await mobile.screenshot({path:'.build/mobile.png',fullPage:true});await mobile.locator('#overview').scrollIntoViewIfNeeded();await mobile.screenshot({path:'.build/mobile-overview.png'});assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile horizontal overflow');await mobile.locator('.site-nav a[href="#/calculator-slide"]').click();await mobile.waitForTimeout(500);await mobile.locator('#processedMode').click();assert.equal(await mobile.locator('#volume').textContent(),'AED 90M');
 await mobile.locator('#processedUnitTrigger').click();await mobile.screenshot({path:'.build/mobile-unit-menu.png'});assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Unit menu mobile overflow');await mobile.locator('#processedUnitMenu [data-value="1000"]').click();assert.equal(await mobile.locator('#volume').textContent(),'AED 90K');
 assert.deepEqual(errors,[]);console.log('Passed: seventeen slide layouts and funding-card navigation; calculator modes, rounding, loss, validation and reset; keyboard input; expanded controls; read mode; mobile layout and controls.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
